site_name: Database Workshop
site_url: https://topdesk.github.io/database-detective/
nav:
  - 'Map': 'index.md'
  - 'Intro Street':
    - 'Connect to your database': intro-street/connect-to-your-database.md
    - 'Read basics': intro-street/read-basics.md
  - 'Sequel Basicland':
    - 'Basic querying': sequel-basicland/basic-querying.md
    - 'Querying with tricky types': sequel-basicland/querying-with-tricky-types.md
    - 'Data modification': sequel-basicland/data-modification.md
  - 'Midtown Join and Aggregation':
    - 'Simple joins': midtown-join-and-aggregation/simple-joins.md
    - 'Aggregation': midtown-join-and-aggregation/aggregation.md
    - 'Complex joins': midtown-join-and-aggregation/complex-joins.md
  - 'Upper Structureland':
    - 'Data modeling': upper-structureland/data-modeling.md
    - 'Practice database design': upper-structureland/practice-database-design.md
    - 'Create and drop tables': upper-structureland/create-and-drop-tables.md
    - 'Practice database creation': upper-structureland/practice-database-creation.md
    - 'Change table structure': upper-structureland/change-table-structure.md
  - 'About':
    - 'Credits': credits.md

docs_dir: material
site_dir: public
use_directory_urls: false
theme: readthedocs
markdown_extensions:
  - pymdownx.superfences
extra_css:
  - css/override.css